# Generated by Django 5.2.14 on 2026-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
