# Generated by Django 5.2.14 on 2026-06-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_unique_together_booking_time_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', 'time_start']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'name']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['room', 'number']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('cancelled', 'Скасоване')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='bookings.room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['workspace', 'booking_date', 'status'], name='bookings_bo_workspa_b7e31a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_date'], name='bookings_bo_user_id_2f3cfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('room', 'number'), name='unique_workspace_number_per_room'),
        ),
    ]
